/* eslint-disable no-useless-escape */
export default (item) => {
  const pyDocs = {
    abs: '<b>abs</b> — get the absolute value of a number<br>Example:<pre>abs(-13)</pre>',
    all: '<b>all</b> — check if all elements of an iterable are true<br>Example:<pre>if all(el > 0 for el in my_list):\n    print(\'All are greater than 0\')</pre>',
    and: '<b>and</b> — logical "and" operator for combining conditions<br>Example:<pre>if x > 0 and y > 0:</pre>',
    any: '<b>any</b> — check if any element of an iterable is true<br>Example:<pre>if any(el > 0 for el in my_list):\n    print(\'At least one is greater than 0\')</pre>',
    as: `<b>as</b> — give an imported module or object a different name (alias)<br>Example:<pre>import math as m\n\nwith open('file.txt') as f:</pre>`,
    bin: '<b>bin</b> — convert an integer to a binary string<br>Example:<pre>bin(17) # "0b10001"</pre>',
    bool: '<b>bool</b> — convert a value to a Boolean (True or False)<br>Example:<pre>bool(17)       # True\nbool([1, 2, 3])  # True\nbool("")       # False</pre>',
    break: '<b>break</b> — exit a loop prematurely<br>Example:<pre>while True:\n    if x > 10:\n        break</pre>',
    chr: '<b>chr</b> — get a character from an integer Unicode code<br>Example:<pre>chr(65) # \'A\'</pre>',
    continue: '<b>continue</b> — skip to the next iteration of a loop<br>Example:<pre>for i in range(10):\n    if i % 2 == 0:\n        continue # skip even numbers\n    print(i)</pre>',
    def: '<b>def</b> — define a function<br>Example:<pre>def add(a, b):\n    return a + b</pre>',
    del: '<b>del</b> — delete a variable, list item, or dictionary entry<br>Example:<pre>my_list = [9, -1, 4]\ndel my_list[1]\n\nmy_dict = {"a": 1, "b": 4}\ndel my_dict["a"]</pre>',
    dict: '<b>dict</b> — create a new dictionary<br>Example:<pre>dict()\ndict([(\'a\', 1), (\'b\', 2)])\ndict(a=1, b=2)</pre>',
    divmod: '<b>divmod</b> — get the quotient and remainder of a division as a pair<br>Example:<pre>quotient, remainder = divmod(10, 3)</pre>',
    elif: '<b>elif</b> — "else if" for conditional branching<br>Example:<pre>if x > 100:\n    print(\'greater than 100\')\nelif x > 50:\n    print(\'from 51 to 100\')</pre>',
    else: '<b>else</b> — run a block of code if an "if" condition is false, or if a loop finishes without "break"<br>Example:<pre>if x > 10:\n    print("Big")\nelse:\n    print("Small")</pre>',
    enumerate: '<b>enumerate</b> — get an index and a value from an iterable at the same time<br>Example:<pre>for i, fruit in enumerate([\'apple\', \'banana\']):\n    print(i, fruit)</pre>',
    False: '<b>False</b> — the boolean value for false<br>Example:<pre>is_active = False</pre>',
    float: '<b>float</b> — convert a string or number to a floating-point number<br>Example:<pre>x = float("3.14")\ny = float(10)</pre>',
    for: '<b>for</b> — loop over the items of a sequence (like a list or string)<br>Example:<pre>for fruit in [\'apple\', \'banana\']:\n    print(fruit)</pre>',
    format: `<b>format</b> — format a value using a specified format<br>Example:<pre>format(123.456, ".2f") # '123.46'</pre>`,
    from: '<b>from</b> — import specific parts of a module<br>Example:<pre>from math import sqrt</pre>',
    hex: `<b>hex</b> — convert an integer to a lowercase hexadecimal string<br>Example:<pre>hex(255) # '0xff'</pre>`,
    id: `<b>id</b> — get the unique memory address (identity) of an object<br>Example:<pre>x = [1, 2]\nprint(id(x))</pre>`,
    if: `<b>if</b> — execute a block of code only if a condition is true<br>Example:<pre>if age >= 18:\n    print("You are an adult.")</pre>`,
    import: `<b>import</b> — bring a module or library into your current script<br>Example:<pre>import math\nprint(math.pi)</pre>`,
    in: `<b>in</b> — check if a value is present in a sequence (list, tuple, string, etc.)<br>Example:<pre>if 'a' in 'apple':\n    print("Found it!")</pre>`,
    input: `<b>input</b> — read a line of text from the user's keyboard input<br>Example:<pre>name = input("Enter your name: ")</pre>`,
    int: `<b>int</b> — convert a value to an integer<br>Example:<pre>x = int("123")\ny = int(3.14)</pre>`,
    is: `<b>is</b> — check if two variables point to the exact same object in memory<br>Example:<pre>a = [1, 2]\nb = a\nc = [1, 2]\na is b  # True\na is c  # False</pre>`,
    len: `<b>len</b> — get the number of items in an object (length)<br>Example:<pre>len("hello")    # 5\nlen([1, 2, 3])  # 3</pre>`,
    list: `<b>list</b> — create a list, or convert another iterable to a list<br>Example:<pre>my_list = list((1, 2, 3))</pre>`,
    map: `<b>map</b> — apply a function to every item of an iterable<br>Example:<pre>numbers = [1, 2, 3]\nsquares = map(lambda x: x**2, numbers)\nlist(squares)  # [1, 4, 9]</pre>`,
    max: `<b>max</b> — find the largest item in an iterable or among arguments<br>Example:<pre>max(1, 5, 2)    # 5\nmax([1, 5, 2])  # 5</pre>`,
    min: `<b>min</b> — find the smallest item in an iterable or among arguments<br>Example:<pre>min(1, 5, 2)    # 1\nmin([1, 5, 2])  # 1</pre>`,
    None: `<b>None</b> — represents the absence of a value, often used as a default return value<br>Example:<pre>result = print("Hello") # result is None</pre>`,
    not: `<b>not</b> — logical "not" operator, inverts a boolean value<br>Example:<pre>if not is_ready:\n    print("Please wait.")</pre>`,
    open: `<b>open</b> — open a file and return a file object. Best used with 'with'.<br>Example:<pre>with open("myfile.txt", "r") as f:\n    content = f.read()</pre>`,
    or: `<b>or</b> — logical "or" operator<br>Example:<pre>if has_key or is_admin:\n    print("Access granted.")</pre>`,
    ord: `<b>ord</b> — get the integer Unicode code of a character<br>Example:<pre>ord('A')  # 65</pre>`,
    pow: `<b>pow</b> — raise a number to a power (exponentiation)<br>Example:<pre>pow(2, 3)  # 8 (same as 2**3)</pre>`,
    print: `<b>print</b> — display output to the console<br>Example:<pre>print("Hello, world!")</pre>`,
    range: `<b>range</b> — generate a sequence of numbers<br>Example:<pre>for i in range(5):  # 0, 1, 2, 3, 4\n    print(i)</pre>`,
    repr: `<b>repr</b> — get an official, unambiguous string representation of an object<br>Example:<pre>import datetime\nrepr(datetime.date.today())</pre>`,
    return: `<b>return</b> — exit a function and optionally pass back a value<br>Example:<pre>def add(a, b):\n    return a + b</pre>`,
    reversed: `<b>reversed</b> — get a reverse iterator for a sequence<br>Example:<pre>my_list = [1, 2, 3]\nfor i in reversed(my_list):\n    print(i)  # 3, 2, 1</pre>`,
    round: `<b>round</b> — round a number to a given number of decimal places<br>Example:<pre>round(3.14159, 2)  # 3.14</pre>`,
    set: `<b>set</b> — create a set (an unordered collection of unique items)<br>Example:<pre>my_set = set([1, 2, 2, 3])  # {1, 2, 3}</pre>`,
    sorted: `<b>sorted</b> — return a new sorted list from the items in an iterable<br>Example:<pre>sorted([3, 1, 4, 1, 5, 9])</pre>`,
    str: `<b>str</b> — convert a value to a string<br>Example:<pre>s = str(123)  # '123'</pre>`,
    sum: `<b>sum</b> — add up all the items in an iterable<br>Example:<pre>sum([1, 2, 3, 4])  # 10</pre>`,
    True: `<b>True</b> — the boolean value for true<br>Example:<pre>is_active = True</pre>`,
    tuple: `<b>tuple</b> — create a tuple (an immutable, ordered sequence)<br>Example:<pre>my_tuple = tuple([1, 2, 3])</pre>`,
    type: `<b>type</b> — get the type of an object<br>Example:<pre>type(123)    # <class 'int'>\ntype("abc")  # <class 'str'></pre>`,
    while: `<b>while</b> — create a loop that runs as long as a condition is true<br>Example:<pre>count = 0\nwhile count < 5:\n    print(count)\n    count += 1</pre>`,
    with: `<b>with</b> — simplify cleanup for resources like files (context manager)<br>Example:<pre>with open('file.txt', 'w') as f:\n    f.write('hello')</pre>`,
    zip: `<b>zip</b> — combine multiple iterables into a single iterator of tuples<br>Example:<pre>list(zip([1, 2], ['a', 'b']))\n# [(1, 'a'), (2, 'b')]</pre>`,
    // Standard Object Methods
    add: `<b>add</b> — (set) add an element to a set<br>Example:<pre>my_set = {1, 2}\nmy_set.add(3)</pre>`,
    append: `<b>append</b> — (list) add an item to the end of a list<br>Example:<pre>my_list = [1, 2]\nmy_list.append(3)</pre>`,
    as_integer_ratio: `<b>as_integer_ratio</b> — (float) get the float as a fraction of two integers<br>Example:<pre>(0.5).as_integer_ratio()  # (1, 2)</pre>`,
    bit_length: `<b>bit_length</b> — (int) get the number of bits required to represent an integer<br>Example:<pre>(10).bit_length()  # 4 (for binary 1010)</pre>`,
    capitalize: `<b>capitalize</b> — (str) convert the first character to uppercase and the rest to lowercase<br>Example:<pre>'hello world'.capitalize()  # 'Hello world'</pre>`,
    center: `<b>center</b> — (str) center a string by padding it with a specified character<br>Example:<pre>'hello'.center(11, '-')  # '---hello---'</pre>`,
    clear: `<b>clear</b> — (dict, list, set) remove all items<br>Example:<pre>my_list = [1, 2, 3]\nmy_list.clear()  # my_list is now []</pre>`,
    copy: `<b>copy</b> — (dict, list, set) return a shallow copy<br>Example:<pre>a = [1, 2]\nb = a.copy()</pre>`,
    count: `<b>count</b> — (str, list) count the occurrences of a value<br>Example:<pre>'hello'.count('l')  # 2</pre>`,
    discard: `<b>discard</b> — (set) remove an element if it exists (no error if not found)<br>Example:<pre>my_set = {1, 2, 3}\nmy_set.discard(2)</pre>`,
    encode: `<b>encode</b> — (str) encode the string into bytes<br>Example:<pre>'hello'.encode('utf-8')</pre>`,
    endswith: `<b>endswith</b> — (str) check if the string ends with a specified suffix<br>Example:<pre>'image.jpg'.endswith('.jpg')  # True</pre>`,
    extend: `<b>extend</b> — (list) add the elements of an iterable to the end of the list<br>Example:<pre>a = [1, 2]\na.extend([3, 4])  # a is now [1, 2, 3, 4]</pre>`,
    find: `<b>find</b> — (str) find the lowest index of a substring; returns -1 if not found<br>Example:<pre>'hello'.find('ll')  # 2</pre>`,
    get: `<b>get</b> — (dict) get a value by key, with a default if the key is not found<br>Example:<pre>my_dict = {'a': 1}\nmy_dict.get('b', 'not found')</pre>`,
    index: `<b>index</b> — (str, list) get the index of the first occurrence of a value (error if not found)<br>Example:<pre>'hello'.index('e')  # 1</pre>`,
    insert: `<b>insert</b> — (list) insert an item at a given position<br>Example:<pre>my_list = ['a', 'c']\nmy_list.insert(1, 'b') # ['a', 'b', 'c']</pre>`,
    is_integer: `<b>is_integer</b> — (float) check if a float is a whole number<br>Example:<pre>(3.0).is_integer()  # True</pre>`,
    isalpha: `<b>isalpha</b> — (str) check if all characters are alphabetic<br>Example:<pre>'hello'.isalpha()  # True</pre>`,
    isdigit: `<b>isdigit</b> — (str) check if all characters are digits<br>Example:<pre>'123'.isdigit()  # True</pre>`,
    isspace: `<b>isspace</b> — (str) check if all characters are whitespace<br>Example:<pre>' \t\n'.isspace()  # True</pre>`,
    items: `<b>items</b> — (dict) get a view of the dictionary's (key, value) pairs<br>Example:<pre>for key, value in {'a': 1}.items():\n    print(key, value)</pre>`,
    join: `<b>join</b> — (str) join elements of an iterable into a single string<br>Example:<pre>'-'.join(['a', 'b', 'c'])  # 'a-b-c'</pre>`,
    keys: `<b>keys</b> — (dict) get a view of the dictionary's keys<br>Example:<pre>for key in {'a': 1}.keys():\n    print(key)</pre>`,
    ljust: `<b>ljust</b> — (str) left-justify a string, padding with a specified character<br>Example:<pre>'hi'.ljust(5, '-')  # 'hi---'</pre>`,
    lower: `<b>lower</b> — (str) convert a string to lowercase<br>Example:<pre>'Hello'.lower()  # 'hello'</pre>`,
    lstrip: `<b>lstrip</b> — (str) remove leading whitespace (or specified characters)<br>Example:<pre>'  hello'.lstrip()  # 'hello'</pre>`,
    partition: `<b>partition</b> — (str) split the string at the first occurrence of a separator<br>Example:<pre>'a=b'.partition('=')  # ('a', '=', 'b')</pre>`,
    pop: `<b>pop</b> — (list, dict) remove and return an item (by index for list, by key for dict)<br>Example:<pre>my_list = [1, 2, 3]\nmy_list.pop()  # returns 3</pre>`,
    popitem: `<b>popitem</b> — (dict) remove and return the last inserted (key, value) pair<br>Example:<pre>{'a': 1, 'b': 2}.popitem()</pre>`,
    remove: `<b>remove</b> — (list, set) remove the first occurrence of a value<br>Example:<pre>my_list = ['a', 'b', 'a']\nmy_list.remove('a')</pre>`,
    replace: `<b>replace</b> — (str) replace all occurrences of a substring with another<br>Example:<pre>'hello'.replace('l', 'x')  # 'hexxo'</pre>`,
    reverse: `<b>reverse</b> — (list) reverse the elements of the list in-place<br>Example:<pre>my_list = [1, 2, 3]\nmy_list.reverse() # my_list is now [3, 2, 1]</pre>`,
    rfind: `<b>rfind</b> — (str) find the highest index of a substring; returns -1 if not found<br>Example:<pre>'ab-ab'.rfind('ab')  # 3</pre>`,
    rindex: `<b>rindex</b> — (str) find the highest index of a substring (error if not found)<br>Example:<pre>'ab-ab'.rindex('ab')  # 3</pre>`,
    rjust: `<b>rjust</b> — (str) right-justify a string, padding with a specified character<br>Example:<pre>'hi'.rjust(5, '-')  # '---hi'</pre>`,
    rpartition: `<b>rpartition</b> — (str) split the string at the last occurrence of a separator<br>Example:<pre>'a=b=c'.rpartition('=')  # ('a=b', '=', 'c')</pre>`,
    rsplit: `<b>rsplit</b> — (str) split a string from the right<br>Example:<pre>'a b c'.rsplit(' ', 1)  # ['a b', 'c']</pre>`,
    rstrip: `<b>rstrip</b> — (str) remove trailing whitespace (or specified characters)<br>Example:<pre>'hello  '.rstrip()  # 'hello'</pre>`,
    sort: `<b>sort</b> — (list) sort the list in-place<br>Example:<pre>my_list = [3, 1, 2]\nmy_list.sort()  # my_list is now [1, 2, 3]</pre>`,
    split: `<b>split</b> — (str) split a string into a list of substrings<br>Example:<pre>'a-b-c'.split('-')  # ['a', 'b', 'c']</pre>`,
    splitlines: `<b>splitlines</b> — (str) split a string into a list of lines<br>Example:<pre>'a\nb\nc'.splitlines()  # ['a', 'b', 'c']</pre>`,
    startswith: `<b>startswith</b> — (str) check if the string starts with a specified prefix<br>Example:<pre>'hello'.startswith('he')  # True</pre>`,
    strip: `<b>strip</b> — (str) remove both leading and trailing whitespace<br>Example:<pre>'  hello  '.strip()  # 'hello'</pre>`,
    title: `<b>title</b> — (str) convert the first character of each word to uppercase<br>Example:<pre>'hello world'.title()  # 'Hello World'</pre>`,
    update: `<b>update</b> — (dict) update the dictionary with key/value pairs from another<br>Example:<pre>d1 = {'a': 1}\nd1.update({'b': 2})</pre>`,
    upper: `<b>upper</b> — (str) convert a string to uppercase<br>Example:<pre>'hello'.upper()  # 'HELLO'</pre>`,
    values: `<b>values</b> — (dict) get a view of the dictionary's values<br>Example:<pre>for val in {'a': 1, 'b': 2}.values():\n    print(val)</pre>`,
    zfill: `<b>zfill</b> — (str) pad a numeric string on the left with zeros<br>Example:<pre>'42'.zfill(5)  # '00042'</pre>`,
  };
  const curDocHtml = pyDocs[item.caption];
  if (curDocHtml) item.docHTML = curDocHtml;
};
